import { assertEquals, assertThrows } from "jsr:@std/assert@1";
import { channelMatches, durationPlausible, parseCatalog, rowToSQL, seedSQL, titleMatches } from "./verify_lib.ts";

Deno.test("a row title must be a prefix of the oEmbed title, case and punctuation aside", () => {
  assertEquals(titleMatches("30 Min Pull Day", "30 MIN PULL DAY | Back & Biceps"), true);
  assertEquals(titleMatches("30 Min Push Day", "30 MIN PULL DAY | Back & Biceps"), false);
});

Deno.test("a stated length in the title must be within ten percent of the duration", () => {
  assertEquals(durationPlausible("30 Min Pull Day", 1780), true);
  assertEquals(durationPlausible("30 Min Pull Day", 2400), false);
  assertEquals(durationPlausible("Pull Day", 2400), true);
});

Deno.test("a row becomes one insert with arrays and a verified timestamp", () => {
  const sql = rowToSQL({
    youtube_id: "abc123XYZ_-", title: "30 Min Pull Day", channel: "Caroline Girvan", duration_s: 1780,
    goal: ["strength", "hypertrophy"], split: "pull", muscles: ["back", "biceps"], equipment: ["dumbbells"], intensity: 2,
  }, "2026-09-15T09:00:00Z");
  assertEquals(sql.includes("'abc123XYZ_-'"), true);
  assertEquals(sql.includes("array['strength','hypertrophy']"), true);
  assertEquals(sql.includes("'2026-09-15T09:00:00Z'"), true);
});

Deno.test("the catalog rejects unknown vocabulary and bad ids", () => {
  assertThrows(() => parseCatalog(JSON.stringify([{ youtube_id: "short", title: "x", channel: "c", duration_s: 60, goal: ["strength"], split: "push", muscles: [], equipment: [], intensity: 2 }])));
  assertThrows(() => parseCatalog(JSON.stringify([{ youtube_id: "abc123XYZ_-", title: "x", channel: "c", duration_s: 60, goal: ["cardio"], split: "push", muscles: [], equipment: [], intensity: 2 }])));
  assertEquals(parseCatalog(JSON.stringify([{ youtube_id: "abc123XYZ_-", title: "x", channel: "c", duration_s: 60, goal: ["strength"], split: "push", muscles: [], equipment: ["none"], intensity: 2 }])).length, 1);
});

Deno.test("a channel matches case and spacing aside, and nothing else", () => {
  assertEquals(channelMatches("Sydney Cummings Houdyshell", "SYDNEY  CUMMINGS\tHOUDYSHELL "), true);
  assertEquals(channelMatches("Caroline Girvan", "Caroline Girvan"), true);
  assertEquals(channelMatches("Caroline Girvan", "Caroline Girvan Fitness"), false);
});

Deno.test("the seed ends with a delete naming every verified id, so a run is a full sync", () => {
  const row = (id: string) => ({
    youtube_id: id, title: "30 Min Pull Day", channel: "Caroline Girvan", duration_s: 1780,
    goal: ["strength"], split: "pull", muscles: ["back"], equipment: ["dumbbells"], intensity: 2,
  });
  const sql = seedSQL([row("abc123XYZ_-"), row("bbc123XYZ_-")], "2026-09-15T09:00:00Z");
  assertEquals(sql.split("\n")[0].startsWith("-- Generated by"), true);
  assertEquals((sql.match(/^insert into/gm) ?? []).length, 2);
  const sweep = sql.trimEnd().split("\n").at(-1)!;
  assertEquals(sweep, "delete from public.workout_videos where youtube_id not in ('abc123XYZ_-','bbc123XYZ_-');");
});
