// Verifies every catalog row against YouTube's keyless oEmbed endpoint and
// writes the seed migration. Run: deno run --allow-net --allow-read --allow-write scripts/catalog/verify.ts
import { durationPlausible, parseCatalog, rowToSQL, titleMatches } from "./verify_lib.ts";

const rows = parseCatalog(await Deno.readTextFile("scripts/catalog/catalog.json"));
const verifiedAt = new Date().toISOString();
const failures: string[] = [];
const statements: string[] = [];
for (const row of rows) {
  const url = `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${row.youtube_id}&format=json`;
  const response = await fetch(url);
  if (!response.ok) { failures.push(`${row.youtube_id}: oEmbed ${response.status}`); continue; }
  const body = await response.json() as { title: string; author_name: string };
  if (!titleMatches(row.title, body.title)) failures.push(`${row.youtube_id}: title "${body.title}" does not start with "${row.title}"`);
  if (!durationPlausible(row.title, row.duration_s)) failures.push(`${row.youtube_id}: duration ${row.duration_s}s disagrees with the title`);
  if (body.author_name.toLowerCase() !== row.channel.toLowerCase()) failures.push(`${row.youtube_id}: channel is "${body.author_name}", not "${row.channel}"`);
  statements.push(rowToSQL(row, verifiedAt));
}
if (failures.length) { console.error(failures.join("\n")); Deno.exit(1); }
const header = "-- Generated by scripts/catalog/verify.ts. Edit scripts/catalog/catalog.json and rerun; do not edit by hand.\n";
await Deno.writeTextFile("supabase/migrations/20260915090100_workout_videos_seed.sql", header + statements.join("\n") + "\n");
console.log(`verified ${rows.length} videos`);
