-- A curated catalog of verified YouTube workout videos. Rows are written
-- only by migrations (the seed generated by scripts/catalog/verify.ts) via
-- the service role; signed-in users get read-only access and no insert,
-- update or delete grant.
create table public.workout_videos (
  youtube_id   text primary key,
  title        text not null,
  channel      text not null,
  duration_s   integer not null check (duration_s > 0),
  goal         text[] not null,        -- strength | hypertrophy | endurance | mobility
  split        text not null,          -- push | pull | legs | upper | lower | full | core | arms | chest | back | shoulders | mobility | cardio
  muscles      text[] not null default '{}',
  equipment    text[] not null default '{}', -- none | dumbbells | barbell | bands | machine | kettlebell
  intensity    smallint not null check (intensity between 1 and 3),
  verified_at  timestamptz not null,
  updated_at   timestamptz not null default now()
);
alter table public.workout_videos enable row level security;
grant select on public.workout_videos to authenticated;
create policy "catalog is readable when signed in" on public.workout_videos
  for select to authenticated using (true);
